"""created author routes and table with fk broken

Revision ID: 2ea50fefe857
Revises: 141a63e9defd
Create Date: 2022-11-10 06:36:23.440720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea50fefe857'
down_revision = '141a63e9defd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('name', sa.String(), nullable=True))
    op.drop_constraint('author_author_id_fkey', 'author', type_='foreignkey')
    op.drop_column('author', 'description')
    op.drop_column('author', 'title')
    op.drop_column('author', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('author', sa.Column('title', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('author', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('author_author_id_fkey', 'author', 'book', ['author_id'], ['id'])
    op.drop_column('author', 'name')
    # ### end Alembic commands ###
